# Generated by Django 3.1.7 on 2021-03-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rceita',
            new_name='Receita',
        ),
    ]
